### ISSUE TITLE
Improve Navbar

### ISSUE THREAD

**Issue by hound77** [hound77/jwoc-archive#1]
create a sticky navbar...!!!

**Comment by shreetama123** [comment]
Hello @hound77 , I want to contribute in this

**Comment by Janhabi-Mukherjee** [comment]
Hey ..I want to work on it

**Comment by hound77** [comment]
@Janhabi-Mukherjee go ahead

**Comment by hound77** [comment]
@shreetama123  go ahead

**Comment by Pabitra145** [comment]
As a part of JWOC I would like to work on it

**Comment by Sayak-0512** [comment]
I would like to work on this issue!
