### ISSUE TITLE
Improve landing page

### ISSUE THREAD

**Issue by hound77** [hound77/jwoc-archive#17]
- improve UI of explore button
- typewriter type effect for displaying text
- any improvement you think suitable

**Comment by heyankit78** [comment]
@hound77 
I would like to do this work
I am the part of JWOC

**Comment by hound77** [comment]
@heyankit78 go ahead

**Comment by sagnik008** [comment]
I want to contribute to this issue

**Comment by sagnik008** [comment]
@hound77 it is already 2 days passed it was assigned to someone else... Plz give me a chance so that i can give it a try:)

**Comment by heyankit78** [comment]
@sagnik008 I am working on these.

**Comment by hound77** [comment]
issue solved
