### ISSUE TITLE
3d flipping cards with rounded edges for team section

### ISSUE THREAD

**Issue by hound77** [hound77/jwoc-archive#2]
![Screenshot 2021-01-18 180223](https://user-images.githubusercontent.com/50631450/104915952-6434c800-59b7-11eb-9406-c289f26ac46b.png)

**Comment by tusharjain0022** [comment]
I would like to work on this issue.

**Comment by hound77** [comment]
@tusharjain0022 go ahead

**Comment by Niveditha18** [comment]
I would like to contribute I'm from jwoc

**Comment by hound77** [comment]
good work @tusharjain0022
