### ISSUE TITLE
create contributor.md

### ISSUE THREAD

**Issue by hound77** [hound77/jwoc-archive#22]
update name of all them contributor make something like a collage 
- a pic of contributor 
- github profile link

**Comment by Swatilekha-Roy** [comment]
I would like to try and work on this this. Could you kindly assign me? I am a mentee in JWOC and my Discord id is @oh_laugh_hugs.

**Comment by Nikhita28** [comment]
I would like to work on this as a mentee at JWoC.

**Comment by hound77** [comment]
@Nikhita28 you work on this
