### ISSUE TITLE
primary slider for gallery section 

### ISSUE THREAD

**Issue by hound77** [hound77/jwoc-archive#3]
![Screenshot 2021-01-18 181323](https://user-images.githubusercontent.com/50631450/104917075-f093ba80-59b8-11eb-8efa-e8b04ebc8783.png)

as viewable in this picture make a slider for enlarge view of images

**Comment by syedmazharaliraza** [comment]
Greetings @hound77 , I would like to work on this under JWOC. Please assign the same

**Comment by hound77** [comment]
@syedmazharaliraza go ahead

**Comment by Niveditha18** [comment]
I would like to contribute

**Comment by Vinamrata1086** [comment]
Can I work on this issue? (JWOC)
