### ISSUE TITLE
Improving particular features on landing page

### ISSUE THREAD

**Issue by Swatilekha-Roy** [hound77/jwoc-archive#37]
- fixing the social link of landing page
- giving space between button and text.
- #37

**Comment by Swatilekha-Roy** [comment]
I would like to try and work on this this. Could you kindly assign me? I am a mentee in JWOC and my Discord id is @oh_laugh_hugs.

**Comment by hound77** [comment]
@Swatilekha-Roy go ahead

**Comment by hound77** [comment]
@Swatilekha-Roy good work
