### ISSUE TITLE
project section initial 

### ISSUE THREAD

**Issue by hound77** [hound77/jwoc-archive#4]
![maxr](https://user-images.githubusercontent.com/50631450/104918839-5aad5f00-59bb-11eb-85e6-ee07097d0c04.jpg)

create card for project section it will have three section 
   - image at top
   - than text about project
   - gitlink of project and project makers' profile

**Comment by Janhabi-Mukherjee** [comment]
Hello .....I would like to work on it.

**Comment by hound77** [comment]
@Janhabi-Mukherjee go ahead
