### ISSUE TITLE
horizontal slider is active in project page  fix it

### ISSUE THREAD

**Issue by hound77** [hound77/jwoc-archive#42]
![Screenshot 2021-01-25 031052](https://user-images.githubusercontent.com/50631450/105644317-07f00d80-5ebb-11eb-91af-4ef71c296dc7.png)

**Comment by hound77** [comment]
fix this issue

**Comment by sagnik008** [comment]
I want to work to fix the issue

**Comment by Swatilekha-Roy** [comment]
I would like to try and work on this. Could you kindly assign me? I am a mentee in JWOC and my Discord id is @oh_laugh_hugs.

**Comment by shreetama123** [comment]
I would like to work on it

**Comment by niloysikdar** [comment]
Want to work on the issue.

**Comment by hound77** [comment]
@Niloy-Sikdar-001 go ahead
