### ISSUE TITLE
Create Footer

### ISSUE THREAD

**Issue by hound77** [hound77/jwoc-archive#5]
![footer](https://user-images.githubusercontent.com/50631450/104921223-0906d380-59bf-11eb-8dd8-a1daf9e528c8.png)

add footer with three rows somewhat like this one 
 - jwoc (two line about it) with logo
 - contact section with icons for linkedin git fb twitter
 - address section

**Comment by Nikhita28** [comment]
I want to work on this as a mentee of JWoC

**Comment by hound77** [comment]
@Nikhita28 go ahead you can work on it.

**Comment by Pabitra145** [comment]
As a part of JWOC I would like to work on it

**Comment by hound77** [comment]
@Nikhita28 great work try mentioning issue number in pr from next time and always put footer outside body tag
