### ISSUE TITLE
Adding some responsiveness to the project page 

### ISSUE THREAD

**Issue by niloysikdar** [hound77/jwoc-archive#55]
Adding some responsiveness to the project page for project cards. Currently, it is not perfectly aligned for small screen devices .

![Screenshot (211)](https://user-images.githubusercontent.com/58071992/106085677-a47a1000-6146-11eb-84f0-bb6d54b27584.png)

**Comment by niloysikdar** [comment]
Want to fix this .

**Comment by hound77** [comment]
@Niloy-Sikdar-001  go ahead
