### ISSUE TITLE
Landing page 

### ISSUE THREAD

**Issue by hound77** [hound77/jwoc-archive#6]
Create a landing page in any way you want. you can show your creativity here but it must have link to index page

**Comment by heyankit78** [comment]
I would like to work on this
I am the part of JWOC

**Comment by heyankit78** [comment]
I would like to work on this 
I am the part of JWOC

**Comment by hound77** [comment]
@heyankit78 go ahead

**Comment by Pabitra145** [comment]
As a part of JWOC I would like to work on it

**Comment by hound77** [comment]
@heyankit78 please provide proper link to index page and image link for background
