### ISSUE TITLE
Adding more responsiveness and improving some features on landing page

### ISSUE THREAD

**Issue by Swatilekha-Roy** [hound77/jwoc-archive#60]
Working on quite a few issues of the landing page:
- change glow color of the social icons to better suit the color coding of rest of website
- enhance responsiveness
- change font-size
- prevent typewritten text motion from overlapping on smaller screens
- remove horizontal and vertical whitespace.

If this is deemed as a permissible issue, I would really like to try working on it.

**Comment by hound77** [comment]
@Swatilekha-Roy go ahead
