### ISSUE TITLE
fix horizontal scroll in mobile view of landing page

### ISSUE THREAD

**Issue by hound77** [hound77/jwoc-archive#72]
![WhatsApp Image 2021-02-06 at 12 45 19](https://user-images.githubusercontent.com/50631450/107112012-74cfb400-687a-11eb-839c-3cbbb6bad358.jpeg)

**Comment by harshita2216** [comment]
I would like to contribute to this issue.

**Comment by hound77** [comment]
@harshita2216 assigned
