### ISSUE TITLE
Adding direction-aware image hover effects on team section

### ISSUE THREAD

**Issue by Swatilekha-Roy** [hound77/jwoc-archive#83]
- Adding a direction- aware screen hover on all the team cards.

I would like to work on this issue, if it's possible. I am a mentee in JWOC.

**Comment by hound77** [comment]
@Swatilekha-Roy  go ahead

**Comment by gaurav24072002** [comment]
Hey !! I am new to this project Please tell which hover effect you want on team cards??
I'll wait for your reply...
